# Generated by Django 4.2 on 2023-04-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('positive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion1', models.IntegerField()),
                ('criterion2', models.IntegerField()),
                ('criterion3', models.IntegerField()),
                ('criterion4', models.IntegerField()),
                ('criterion5', models.IntegerField()),
                ('criterion1_task1_grade', models.IntegerField()),
                ('criterion1_task2_grade', models.IntegerField()),
                ('criterion3_task1_grade', models.IntegerField()),
                ('criterion3_task2_grade', models.IntegerField()),
                ('criterion3_task3_grade', models.IntegerField()),
                ('criterion3_task4_grade', models.IntegerField()),
                ('criterion4_task1_grade', models.IntegerField()),
                ('criterion4_task2_grade', models.IntegerField()),
                ('criterion5_task1_grade', models.IntegerField()),
                ('criterion5_task2_grade', models.IntegerField()),
                ('criterion5_task3_grade', models.IntegerField()),
                ('criterion5_task4_grade', models.IntegerField()),
                ('criterion5_task5_grade', models.IntegerField()),
            ],
        ),
    ]
